create extension if not exists pgcrypto;

create table if not exists public.bot_users (
  phone text primary key,
  blocked boolean not null default false,
  preferred_mode text not null default 'normal',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.batch_sessions (
  id uuid primary key default gen_random_uuid(),
  phone text not null references public.bot_users(phone),
  status text not null default 'open' check (status in ('open', 'closed', 'expired')),
  max_items integer not null default 10 check (max_items between 1 and 10),
  received_count integer not null default 0 check (received_count >= 0),
  processed_count integer not null default 0 check (processed_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  expires_at timestamptz not null default (now() + interval '5 minutes'),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create unique index if not exists batch_sessions_one_open_per_phone
  on public.batch_sessions(phone) where status = 'open';

create table if not exists public.processing_events (
  id bigint generated by default as identity primary key,
  message_id text unique not null,
  phone text not null references public.bot_users(phone),
  batch_id uuid references public.batch_sessions(id),
  processing_type text not null check (processing_type in ('sticker', 'batch_sticker')),
  status text not null default 'accepted' check (status in ('accepted', 'processing', 'success', 'rejected', 'error')),
  input_bytes bigint check (input_bytes is null or input_bytes >= 0),
  output_bytes bigint check (output_bytes is null or output_bytes >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists processing_events_phone_created_idx
  on public.processing_events(phone, created_at desc);
create index if not exists processing_events_status_idx
  on public.processing_events(status);
create index if not exists batch_sessions_phone_status_idx
  on public.batch_sessions(phone, status);

alter table public.bot_users enable row level security;
alter table public.batch_sessions enable row level security;
alter table public.processing_events enable row level security;

revoke all on table public.bot_users from public, anon, authenticated;
revoke all on table public.batch_sessions from public, anon, authenticated;
revoke all on table public.processing_events from public, anon, authenticated;
