create table if not exists public.admin_revoked_sessions (
  token_hash text primary key check (length(token_hash) = 64),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists admin_revoked_sessions_expires_idx
  on public.admin_revoked_sessions(expires_at);

create table if not exists public.admin_action_audit (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('user_blocked', 'user_unblocked')),
  phone_masked text not null,
  created_at timestamptz not null default now()
);

create index if not exists admin_action_audit_created_idx
  on public.admin_action_audit(created_at desc);

alter table public.admin_revoked_sessions enable row level security;
alter table public.admin_action_audit enable row level security;
revoke all on table public.admin_revoked_sessions from public, anon, authenticated;
revoke all on table public.admin_action_audit from public, anon, authenticated;

create or replace function public.admin_revoke_session(p_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.admin_revoked_sessions where expires_at <= now();
  insert into public.admin_revoked_sessions(token_hash, expires_at)
  values (p_token_hash, now() + interval '8 hours')
  on conflict (token_hash) do update set expires_at = excluded.expires_at;
  return true;
end;
$$;

create or replace function public.admin_is_session_revoked(p_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.admin_revoked_sessions where expires_at <= now();
  return exists(select 1 from public.admin_revoked_sessions where token_hash = p_token_hash and expires_at > now());
end;
$$;

create or replace function public.admin_set_user_blocked(p_phone text, p_blocked boolean)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  changed boolean;
begin
  update public.bot_users set blocked = p_blocked where phone = p_phone returning true into changed;
  if not coalesce(changed, false) then return false; end if;
  insert into public.admin_action_audit(action, phone_masked)
  values (case when p_blocked then 'user_blocked' else 'user_unblocked' end, public.admin_mask_phone(p_phone));
  return true;
end;
$$;

revoke all on function public.admin_revoke_session(text) from public, anon, authenticated;
revoke all on function public.admin_is_session_revoked(text) from public, anon, authenticated;
revoke all on function public.admin_set_user_blocked(text, boolean) from public, anon, authenticated;
grant execute on function public.admin_revoke_session(text) to service_role;
grant execute on function public.admin_is_session_revoked(text) to service_role;
grant execute on function public.admin_set_user_blocked(text, boolean) to service_role;
